import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main className={styles.main}>
          <h1>Welcome to Home</h1>
          <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique perspiciatis minima quo quam iusto sed, aspernatur, iure vitae, quaerat nisi unde officia. Officiis, nobis natus necessitatibus eligendi earum non tenetur at possimus sunt voluptates cum illo odio exercitationem fuga. Pariatur, et. Iusto, cumque. Odit, autem non consectetur maxime reprehenderit nobis ut doloribus suscipit, labore, laborum quod quia. Animi consectetur vel, blanditiis dolores libero velit odio reiciendis eaque. Voluptate, quibusdam magnam quidem qui ullam explicabo, doloremque dignissimos reprehenderit aspernatur blanditiis suscipit possimus minima provident laborum impedit! Deleniti quae quidem possimus facilis maxime vel veniam ducimus, sint eos architecto quasi ut, asperiores iure ex perferendis amet veritatis ab deserunt ipsam id. Distinctio odit, totam molestias quo consequatur dolores voluptatem ipsa ut animi? Ipsa pariatur voluptate labore ut debitis at similique cupiditate sequi, porro odio, exercitationem rem fuga id ea molestiae quibusdam nobis quisquam. Expedita dolor voluptates officia? Distinctio cupiditate dolorem quidem, tenetur fugiat non, velit amet quasi labore repellat, voluptatem vero ea doloribus eveniet voluptates voluptatum expedita in fuga aspernatur? Aliquid soluta sit ullam nulla, veniam laborum suscipit laudantium minus aut quae id, neque, corporis error quia odio harum odit. Temporibus nobis hic, nemo culpa dolor nam et! Voluptates et repudiandae atque.</p>
        </main>
      </div>
    </>
  );
}
